steps:
- id: install-app
  name: 'dtzar/helm-kubectl:3.5.0'
  args: [ 'scripts/export_k8s.sh' ]
  env:
   - 'KUBECONFIG=/workspace/.kube/config'
   - '_CLIENT_TOKENS=$_CLIENT_TOKENS'
   - '_KUBE_CONFIG=$_KUBE_CONFIG'
