steps:
- id: extract-files
  name: 'alpine'
  args: [ 'scripts/export_k8s.sh' ]

- id: install-app
  name: 'dtzar/helm-kubectl:3.5.0'
  args: ['upgrade', 'parser', 'parser', '--install']
  env:
   - 'KUBECONFIG=/workspace/.kube/config'
