steps:
- name: 'gcr.io/cloud-builders/kubectl'
  id: Exporting-kubectl-config
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-test-1'
  - 'KUBECONFIG=/workspace/.kube/config'
  args: ['cluster-info']

- id: install-app
  name: 'dtzar/helm-kubectl:3.5.0'
  args: [ 'helm', 'upgrade', 'parser', 'parser', '--install' ]
  env:
   - 'KUBECONFIG=/workspace/.kube/config'
